### ISSUE TITLE
GitHub 2FA support

### ISSUE THREAD

**Issue by tcby45** [guyzmo/git-repo#39] opened 2016-10-10 18:25 UTC
I have 2FA enabled on my GitHub account. When I ran `git repo config`, this happened:

```
Do you want to configure the github service?
    [Yn]> y
Please enter your credentials to connect to the service:
username> tcby45
password>
Fatal error: 401 Must specify two-factor authentication OTP code.
```
Could you please either include a 2FA check on the account (then a prompt for the code), or possibly ask whether to authenticate by personal access token or user/pass?

**Comment by guyzmo** [comment] 2016-10-10 19:01
well, the idea is that when you enter login/password with github, it's actually creating a personal token for git-repo, it's *NOT* keeping your credentials. 

I agree it's a bit too cryptic and needs more explanation, though. But if you don't want to share your credentials, just can edit `~/.gitconfig` manually!

**Comment by guyzmo** [comment] 2016-10-10 19:02
About github 2FA per se, it's definitely a good idea, but it's definitely low priority for me, way after implementing proper OAuth for bitbucket.

**Comment by jandrusk** [comment] 2016-10-10 19:32
Just ran into the same thing and would like 2FA support as well.

**Comment by guyzmo** [comment] 2016-10-10 22:05
how would you see the 2FA happening? Just for the first time authentication? Or each time you're using the CLI tool?

**Comment by guyzmo** [comment] 2016-10-10 22:08
I'd be happy to see a proper usage use case for accepting the 2FA as a feature.

**Comment by tcby45** [comment] 2016-10-11 01:18
With what you've described above, here's an ideal situation:

1. User runs `git repo config` for the first time and elects to use GitHub.
2. Wizard prompts user for username and password.
3. Two options:

a. User **with** 2FA enabled sends username and password. Wizard receives `X-GitHub-OTP: required; :2fa-type` header (see [here](https://developer.github.com/v3/auth/#working-with-two-factor-authentication)). User is prompted for OTP password, which is sent, in the `X-GitHub-OTP` header, along with another request containing the username and password. GitHub approves, and the wizard continues as normal.
b. User **without** 2FA enabled sends username and password. GitHub approves, and the wizard continues as normal.

This way, anyone with 2FA enabled (i.e. those who have any sense of security) can take advantage of the wizard *and* `git-repo` as a whole.

**Comment by guyzmo** [comment] 2016-10-11 01:42
oooh alright… we'll have to check with @sigmavirus24 how the [sigmavirus24/github3.py](https://github.com/sigmavirus24/github3.py/) library would handle 2FA, and I might make a patch for that.

**Comment by guyzmo** [comment] 2016-10-11 01:43
looks like it's in the lib sigmavirus24/github3.py#167 so it's definitely possible to add support in the client.

**Comment by guyzmo** [comment] 2016-10-12 23:50
I've just pushed a new branch that supports 2FA auth:

https://github.com/guyzmo/git-repo/tree/features/2FA_github

the only issue is that it crashes with a 422 Validation Failed when trying to create a token for the tool.

Please test and hack based on that commit 0c29743b596cc4be08adea2e788aa66938087aaf

**Comment by tcby45** [comment] 2016-10-13 11:00
Downloaded and installed from that branch, got the following error: `Fatal error: 'GitHub' object has no attribute 'token'`

**Comment by guyzmo** [comment] 2016-10-13 16:46
oh, I'm sorry, I forgot a bit of code when I made the commit ☺

Though it's still failing with the 422 error.

I guess that we need to patch the [github3.py](https://github.com/sigmavirus24/github3.py/blob/develop/github3/github.py#L181) code so that it supports the
[two_factor_auth_callback setting](https://github.com/sigmavirus24/github3.py/blob/develop/github3/github.py#L768) as shown in the `login()` method.

As you can see, on the `git-repo` side, the code implementing auth is pretty minimalistic…

**Comment by sigmavirus24** [comment] 2016-10-13 19:33
`self.session.basic_auth()` does nothing with the 2FA callback work. You'll need to tell us you're going to use the 2FA callback (at the moment just doing `gh.login(two_factor_callback=...)` and then using authorize. It will still catch it for you

**Comment by guyzmo** [comment] 2016-10-13 19:48
hi @sigmavirus24 🖖, very nice of you to join the discussion!

well, that's what I've actually implemented [there](https://github.com/guyzmo/git-repo/blob/features/2FA_github/git_repo/services/ext/github.py#L200,L204), and for some reason it's failing with a 422.

So let's dig into that…

**Comment by guyzmo** [comment] 2016-10-13 20:01
…ok I went too fast when I first tried. 

The issue is that when there's already a key with the same name on github, it's failing with a `422 Unprocessable Entity`, making some confusion.

So basically, the 2FA code is working! I'm not sure how I can make a meaningful regression test for that, though… ☹

**Comment by guyzmo** [comment] 2016-10-13 21:00
ok, it's merged in master. I'll roll it out with the next release.

**Closed** 2016-10-16 00:41 UTC
Labels: enhancement, ready
