### ISSUE TITLE
git lab clone fails for new repository

### ISSUE THREAD

**Issue by ctrngk** [guyzmo/git-repo#129] opened 2017-02-18 08:29 UTC
`git lab clone` does not work as expected for some reasons, shortly after `git lab create`.
Fatal error: fatal: Couldn't find remote ref master
fatal: The remote end hung up unexpectedly

 However, `git clone git@gitlab.com:user/repo.git` works as expected. Could git-repo try this command after failing `git lab clone user/repo`.

**Comment by guyzmo** [comment] 2017-02-19 09:59
About the first issue, it's indeed fixed in the devel branch, and planned for the next minor release, I've been a bit busy on another project in parallel sorry :)

About the second, it's not exactly doing a git clone, but a `git init` and `git fetch`. The issue is caused as I made a stupid assumption that default branch is master. I've partially solved this issue, but it looks like there are still references to `master` in the code. I'll have to check that.

**Comment by guyzmo** [comment] 2017-02-19 10:02
Thank you for reporting! (N.B. I'm editing your post to keep focused: one issue → one topic).

**Comment by ctrngk** [comment] 2017-02-23 01:21
Thank you. This should have been included in beginner tutorials.
Also, from user respective, `git lab clone $USER/foobar` is equivalent to `git clone git@gitlab.com:$USER/foobar`, as well as `git hub clone`.  Maybe a parser to translate to official command?

**Comment by guyzmo** [comment] 2017-02-24 10:35
No, I'll just look forward to make it possible to clone an empty repository, it's on my todo list :)

Basically, I guess I'll be doing a `git init` and `git remote add` upon error with the remote repository existing but being empty.

**Closed** 2017-05-04 14:37 UTC
Labels: enhancement, in progress
